// Code generated by "stringer -type HtmlHandlerType -trimprefix HtmlType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HtmlTypeMeta-0]
	_ = x[HtmlTypeContent-1]
	_ = x[HtmlTypeText-2]
}

const _HtmlHandlerType_name = "MetaContentText"

var _HtmlHandlerType_index = [...]uint8{0, 4, 11, 15}

func (i HtmlHandlerType) String() string {
	if i < 0 || i >= HtmlHandlerType(len(_HtmlHandlerType_index)-1) {
		return "HtmlHandlerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HtmlHandlerType_name[_HtmlHandlerType_index[i]:_HtmlHandlerType_index[i+1]]
}
