// Code generated by "stringer -type ParseState"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParsingStart-0]
	_ = x[ParsingDocument-1]
	_ = x[ParsingMeta-2]
	_ = x[ParsingMetaVal-3]
	_ = x[ParsingHtmlElement-4]
	_ = x[ParsingTermDefinition-5]
	_ = x[ParsingTermExplanation-6]
	_ = x[ParsingSidenoteDefinition-7]
	_ = x[ParsingLinkDefinition-8]
	_ = x[ParsingAttributeList-9]
	_ = x[ParsingAttributeListAfterID-10]
	_ = x[ParsingAttributeListVal-11]
	_ = x[ParsingSection1-12]
	_ = x[ParsingSection1AfterAttributeList-13]
	_ = x[ParsingSection1Content-14]
	_ = x[ParsingSection2-15]
	_ = x[ParsingSection2AfterAttributeList-16]
	_ = x[ParsingSection2Content-17]
	_ = x[ParsingCodeBlock-18]
	_ = x[ParsingCodeBlockAfterAttr-19]
	_ = x[ParsingImage-20]
	_ = x[ParsingBlockquote-21]
	_ = x[ParsingBlockquoteAuthor-22]
	_ = x[ParsingBlockquoteSource-23]
	_ = x[ParsingBlockquoteAfterAttrEnd-24]
	_ = x[ParsingParagraph-25]
	_ = x[ParsingEmphasis-26]
	_ = x[ParsingStrong-27]
	_ = x[ParsingStrikethrough-28]
	_ = x[ParsingMarker-29]
	_ = x[ParsingEmphasisStrong-30]
	_ = x[ParsingEnquoteDouble-31]
	_ = x[ParsingEnquoteAngled-32]
	_ = x[ParsingLinkable-33]
	_ = x[ParsingLinkableAfterHref-34]
	_ = x[ParsingLinkableAfterRef-35]
	_ = x[ParsingSidenoteAfterRef-36]
	_ = x[ParsingSidenoteContent-37]
}

const _ParseState_name = "ParsingStartParsingDocumentParsingMetaParsingMetaValParsingHtmlElementParsingTermDefinitionParsingTermExplanationParsingSidenoteDefinitionParsingLinkDefinitionParsingAttributeListParsingAttributeListAfterIDParsingAttributeListValParsingSection1ParsingSection1AfterAttributeListParsingSection1ContentParsingSection2ParsingSection2AfterAttributeListParsingSection2ContentParsingCodeBlockParsingCodeBlockAfterAttrParsingImageParsingBlockquoteParsingBlockquoteAuthorParsingBlockquoteSourceParsingBlockquoteAfterAttrEndParsingParagraphParsingEmphasisParsingStrongParsingStrikethroughParsingMarkerParsingEmphasisStrongParsingEnquoteDoubleParsingEnquoteAngledParsingLinkableParsingLinkableAfterHrefParsingLinkableAfterRefParsingSidenoteAfterRefParsingSidenoteContent"

var _ParseState_index = [...]uint16{0, 12, 27, 38, 52, 70, 91, 113, 138, 159, 179, 206, 229, 244, 277, 299, 314, 347, 369, 385, 410, 422, 439, 462, 485, 514, 530, 545, 558, 578, 591, 612, 632, 652, 667, 691, 714, 737, 759}

func (i ParseState) String() string {
	if i < 0 || i >= ParseState(len(_ParseState_index)-1) {
		return "ParseState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParseState_name[_ParseState_index[i]:_ParseState_index[i+1]]
}
