// Code generated by "stringer -type TokenType -trimprefix Token"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenMetaStart-1]
	_ = x[TokenMetaKey-2]
	_ = x[TokenMetaVal-3]
	_ = x[TokenMetaEnd-4]
	_ = x[TokenHtmlTagStart-5]
	_ = x[TokenHtmlTagAttrKey-6]
	_ = x[TokenHtmlTagAttrVal-7]
	_ = x[TokenHtmlTagEnd-8]
	_ = x[TokenParagraph-9]
	_ = x[TokenSection1-10]
	_ = x[TokenSection2-11]
	_ = x[TokenCodeBlockStart-12]
	_ = x[TokenCodeBlockEnd-13]
}

const _TokenType_name = "EOFMetaStartMetaKeyMetaValMetaEndHtmlTagStartHtmlTagAttrKeyHtmlTagAttrValHtmlTagEndParagraphSection1Section2CodeBlockStartCodeBlockEnd"

var _TokenType_index = [...]uint8{0, 3, 12, 19, 26, 33, 45, 59, 73, 83, 92, 100, 108, 122, 134}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
